.. Hey, Emacs this is -*- rst -*-

   This file follows reStructuredText markup syntax; see
   http://docutils.sf.net/rst.html for more information.

.. This file is included by *any* other ``.txt`` file. 
   Be careful!!!


.. Links

   Please list here all references that (are likely to) appear in more
   than one file, so to avoid "duplicate link" errors and to control
   the reference target more easily.

   References should be sorted by link name (case-insensitively), to
   make it easy to spot a missing or duplicate reference.

.. _`Torque/PBS`: http://www.adaptivecomputing.com/products/open-source/torque/
.. _`Grid Computing Competence Center`: http://www.gc3.uzh.ch/
.. _`University of Zurich`: http://www.uzh.ch
.. _`GNU General Public License version 3`: http://www.gnu.org/licenses/gpl.html
.. _`Amazon's Elastic Compute Cloud EC2`: http://aws.amazon.com/ec2/
.. _`OpenStack`: http://www.openstack.org/
.. _`Google Compute Engine`: https://cloud.google.com/products/compute-engine/
.. _`Debian GNU/Linux`: http://www.debian.org
.. _`Ubuntu`: http://www.ubuntu.com
.. _`CentOS`: http://www.centos.org/
.. _`SLURM`: https://computing.llnl.gov/linux/slurm/
.. _`Grid Engine`: http://gridengine.info
.. _`Ganglia`: http://ganglia.info
.. _`Hadoop`: http://hadoop.apache.org/
.. _`Ansible`: http://ansible.cc 
.. _`Python`: http://www.python.org
.. _`pip`: https://pypi.python.org/pypi/pip
.. _`PyPI`: https://pypi.python.org/pypi
.. _`github`: https://github.com/
.. _`github elasticluster page`: https://github.com/gc3-uzh-ch/elasticluster
.. _`python virtualenv`: https://pypi.python.org/pypi/virtualenv
.. _`boto library`: https://github.com/boto/boto
.. _`OrangeFS`: http://orangefs.org/
.. _`IPython cluster`: http://ipython.org/ipython-doc/dev/parallel/
.. _`HTCondor`: http://research.cs.wisc.edu/htcondor/
.. _`GlusterFS`: http://www.gluster.org/
.. _`Ceph`: http://ceph.com/
