.. Hey, Emacs this is -*- rst -*-

   This file follows reStructuredText markup syntax; see
   http://docutils.sf.net/rst.html for more information.

.. This file is included by *any* other ``.txt`` file.
   Be careful!!!


.. Links

   Please list here all references that (are likely to) appear in more
   than one file, so to avoid "duplicate link" errors and to control
   the reference target more easily.

   References should be sorted by link name (case-insensitively), to
   make it easy to spot a missing or duplicate reference.

.. _`Amazon's Elastic Compute Cloud EC2`: http://aws.amazon.com/ec2/
.. _`Anaconda`: https://www.anaconda.com/
.. _`Ansible`: http://ansible.com/
.. _`Apache LibCloud`: https://libcloud.readthedocs.io/
.. _`Bigtop`: http://bigtop.apache.org/
.. _`boto library`: https://github.com/boto/boto
.. _`CentOS`: http://www.centos.org/
.. _`Ceph`: http://ceph.com/
.. _`Debian GNU/Linux`: http://www.debian.org
.. _EasyBuild: http://easybuild.readthedocs.io/
.. _`elasticluster`: http://gc3-uzh-ch.github.io/elasticluster/
.. _`example configuration file`: https://github.com/gc3-uzh-ch/elasticluster/raw/master/elasticluster/share/etc/config.template
.. _`Ganglia`: http://ganglia.info
.. _`github elasticluster page`: https://github.com/gc3-uzh-ch/elasticluster
.. _`github elasticluster repository`: https://github.com/gc3-uzh-ch/elasticluster
.. _`github`: https://github.com/
.. _`GlusterFS`: http://www.gluster.org/
.. _`GNU General Public License version 3`: http://www.gnu.org/licenses/gpl.html
.. _`Google Compute Engine`: https://cloud.google.com/products/compute-engine/
.. _`Grid Computing Competence Center`: http://www.gc3.uzh.ch/
.. _`GridEngine`: http://gridengine.info
.. _`Hadoop`: http://hadoop.apache.org/
.. _`Hive`: http://hive.apache.org/
.. _`HTCondor`: http://research.cs.wisc.edu/htcondor/
.. _`IPython cluster`: http://ipython.org/ipython-doc/dev/parallel/
.. _`Jupyter`: http://jupyter.org/
.. _`JupyterHub`: http://jupyterhub.readthedocs.io/
.. _Lmod: http://lmod.readthedocs.io/en/latest/
.. _Lua: http://www.lua.org/
.. _`mailing-list`: https://groups.google.com/forum/#!forum/elasticluster
.. _`OpenStack`: http://www.openstack.org/
.. _`OrangeFS`: http://orangefs.org/
.. _`pip`: https://pypi.python.org/pypi/pip
.. _`PyPI`: https://pypi.python.org/pypi
.. _`python virtualenv`: https://pypi.python.org/pypi/virtualenv
.. _`Python`: http://www.python.org
.. _`R language`: http://www.r-project.org/
.. _`Services and Support for Science IT`: http://www.s3it.uzh.ch/
.. _`SoGE`: https://arc.liv.ac.uk/trac/SGE
.. _`Spark`: http://spark.apache.org/
.. _`SLURM`: https://slurm.schedmd.com/
.. _`Torque/PBS`: http://www.adaptivecomputing.com/products/open-source/torque/
.. _`Ubuntu`: http://www.ubuntu.com
.. _`University of Zurich`: http://www.uzh.ch
.. _`UUID`: https://en.wikipedia.org/wiki/Universally_unique_identifier
